// export const GLLM = "https://sheetdb.io/api/v1/xvqhrhg4y9avq";
export const GLLM = "https://sheet.best/api/sheets/e8876c80-1778-414d-ae68-af6b9ec1289c";

export const PRODUCTS = [
    ["SP Bình Thường",
        [
            ["1 Layer Suncatcher Ornament", "1 Layer Suncatcher Ornament", 1],
            ["1M keyChain Alunium", "1M keyChain Alunium", 1],
            ["1M Photo Building Block", "1M Photo Building Block", 1],
            ["1M Wallet Insert Card", "1M Wallet Insert Card", 1],
            ["2 Layered Acrylic Ornament", "2 Layered Acrylic Ornament", 1],
            ["2 layer mix", "2 layer mix", 1],
            ["2 layer vc", "2 layer vc", 1],
            ["2 Layered Shaker Fridge Magnet", "2 Layered Shaker Fridge Magnet", 1],
            ["2M keyChain Alunium", "2M keyChain Alunium", 2],
            ["2M Leather Keychain", "2M Leather Keychain", 1],
            ["2M Photo Building Block", "2M Photo Building Block", 1],
            ["2M Wallet Insert Card", "2M Wallet Insert Card", 2],
            ["35 layer lop ngoai", "35 layer lop ngoai", 1],
            ["3d led light print base", "3d led light print base", 1],
            ["3d wood base", "3d wood base", 1],
            ["3d woodBase Teemazing", "3d woodBase Teemazing", 1],
            ["3L Acrylic Shaker Keychain", "3L Acrylic Shaker Keychain", 1],
            ["3L Shaker Ornament", "3L Shaker Ornament", 1],
            ["3l Tumble Name Tag", "3l Tumble Name Tag", 1],
            ["3layer wood ornament", "3layer wood ornament", 1],
            ["3 Layered Sticky Note Holder", "3 Layered Sticky Note Holder", 1],
            ["5L Shaker Ornament", "5L Shaker Ornament", 1],
            ["A Custom Shape Keychain With Charm", "A Custom Shape Keychain With Charm", 1],
            ["Acrylic Block", "Acrylic Block", 1],
            ["Acrylic Bookmark", "Acrylic Bookmark", 1],
            ["Acrylic Desk Plaque", "Acrylic Desk Plaque", 1],
            ["Acrylic Plaque", "Acrylic Plaque", 1],
            ["Acrylic Plaque TMZ", "Acrylic Plaque TMZ", 1],
            ["bamboowireless", "Bamboo Wireless", 1],
            ["blank", "blank", 1],
            ["C Plant Pot", "C Plant Pot", 1],
            ["cai gi day", "cai gi day", 1],
            ["candle holder", "candle holder", 1],
            ["Ceramic Flower Vase", "Ceramic Flower Vase", 1],
            ["Ceramic Flower Vase cn", "Ceramic Flower Vase cn", 1],
            ["Ceramic Flower Vase cn nho", "Ceramic Flower Vase cn nho", 1],
            ["Ceramic Jewelry Tray", "Ceramic Jewelry Tray", 1],
            ["Christmas 3D Ball Ornament", "Christmas 3D Ball Ornament", 1],
            ["Christmas Door Ornament", "Christmas Door Ornament", 1],
            ["Christmas Tree Topper", "Christmas Tree Topper", 1],
            ["Clipboard", "Clipboard", 1],
            ["coc30oz", "coc30oz", 1],
            ["Custom 2 Layered Acrylic Keychain", "Custom 2 Layered Acrylic Keychain", 1],
            ["Custom 2 Layered Art Piece", "Custom 2 Layered Art Piece", 1],
            ["Custom Acrylic Name Night Light", "Custom Acrylic Name Night Light", 1],
            ["Custom Acrylic Name Night Light pine", "Custom Acrylic Name Night Light pine", 1],
            ["Custom Acrylic Slider Ornament", "Custom Acrylic Slider Ornament", 1],
            ["Custom Metal Art Piece", "Custom Metal Art Piece", 1],
            ["Custom Money Holder", "Custom Money Holder", 1],
            ["Custom Shape 2-3 Layers Tag", "Custom Shape 2-3 Layers Tag", 1],
            ["Custom Shape Acrylic Block TMZ", "Custom Shape Acrylic Block TMZ", 1],
            ["Custom Shape Acrylic Blocks", "Custom Shape Acrylic Blocks", 1],
            ["Custom Shape Fridge Magnet", "Custom Shape Fridge Magnet", 1],
            ["Custom Shape Photo Light Box", "Custom Shape Photo Light Box", 1],
            ["Custom Wooden Slider Ornament", "Custom Wooden Slider Ornament", 1],
            ["cut metal", "cut metal", 1],
            ["decal", "decal", 1],
            ["Desk Name Plate Night Light", "Desk Name Plate Night Light", 1],
            ["dia nhua", "dia nhua", 1],
            ["dia than 2m", "đĩa than 2m", 2],
            ["dock", "dock", 1],
            ["drink coaster", "drink coaster", 1],
            ["FatherDayZirror", "FatherDayZirror", 1],
            ["flag", "flag", 1],
            ["Glitter Plastic Ornament", "Glitter Plastic Ornament", 1],
            ["Glitter Plastic Ornament 2M", "Glitter Plastic Ornament 2M", 1],
            ["glassOrnament", "glass Ornament", 1],
            ["glassOrnament tron", "glass Ornament tron", 1],
            ["Graduation Cap Topper", "Graduation Cap Topper", 1],
            ["Heart mica 2cm", "Heart mica 2cm", 1],
            ["keyChain mirror", "keyChain mirror", 2],
            ["keyChain normal", "keyChain normal", 2],
            ["Led Light Wood Base TMZ", "Led Light Wood Base TMZ", 1],
            ["Leather Keychain", "Leather Keychain", 1],
            ["Layered Mix Photo Sign", "Layered Mix Photo Sign", 1],
            ["Luminous Painting Lighting Box", "Luminous Painting Lighting Box", 1],
            ["Magnetic Car Visor Photo Clip", "Magnetic Car Visor Photo Clip", 1],
            ["Memorial Garden Stone", "Memorial Garden Stone", 1],
            ["mica fix ornament 1M", "mica fix ornament 1M", 1],
            ["mica fix ornament 2M", "mica fix ornament 2M", 2],
            ["mirror normal", "normal mirror", 1],
            ["mirror normal StrokFile", "mirror normal StrokFile", 1],
            ["new Dock", "new Dock", 1],
            ["NEW transparent ORM 1M", "NEW transparent ORM 1M", 1],
            ["NEW transparent ORM 1M no white", "NEW transparent ORM 1M no white", 1],
            ["NEW transparent ORM 1M Wooden", "NEW transparent ORM 1M Wooden", 1],
            ["NEW transparent ORM 2M", "NEW transparent ORM 2M", 1],
            ["normal", "normal", 1],
            ["normal strokeFile", "normal strokeFile", 1],
            ["normal strokeFile ngang", "normal strokeFile ngang", 1],
            ["ornament go 1M-Singer", "ornament gỗ tấm 1M in xong cắt", 1],
            ["ornament go 2M-1m2x2m4", "ornament gỗ 2M-1m2x2m4", 2],
            ["ornament go 2M-Singer", "ornament gỗ tấm 2M in xong cắt", 2],
            ["ornament led", "ornament led", 1],
            ["ornament mica 1M-Singer", "ornament mica 1M-file đơn", 1],
            ["ornament mica 2M-Singer", "ornament mica 2M-file đơn", 2],
            ["ornament nhom 1M", "ornament nhôm 1M", 1],
            ["ornament nhom 2M", "ornament nhôm 2M", 2],
            ["ornament qua ta nhom", "quả tạ DZT", 2],
            ["ornament su 1M", "ornament sứ", 1],
            ["ornament su 2M", "ornament sứ 2 mặt", 2],
            ["ornament su medalion moi 1M", "ornament su medalion moi 1M", 1],
            ["ornament su medalion moi 2M", "ornament su medalion moi 2M", 2],
            ["ornament vong huong", "ornament vòng hương", 1],
            ["PC glass", "ốp glass", 1],
            ["PC led", "ốp led", 2],
            ["PC luminous", "ốp luminous", 1],
            ["PC silicon", "ốp silicon", 1],
            ["photo album keychain", "photo album keychain", 1],
            ["photo frame lamp", "photo frame lamp", 1],
            ["Photo Magnet", "Photo Magnet", 1],
            ["Photo Magnet 2 3 layer", "Photo Magnet 2 3 layer", 1],
            ["photobox", "photobox", 1],
            ["print metal", "print metal", 1],
            ["puzzle hehe", "puzzle hehe", 0],
            ["reusable school", "reusable school", 1],
            ["Round Plastic Led String Light", "Round Plastic Led String Light", 1],
            ["skinni-20oz", "skinni-20oz", 1],
            ["Skinny-thon", "Skinny-thon", 1],
            ["Stained Glass Ornament", "Stained Glass Ornament", 1],
            ["Stained Glass Ornament type 2", "Stained Glass Ornament type 2", 1],
            ["Stained Glass Suncatcher", "Stained Glass Suncatcher", 1],
            ["Stained Glass Suncatcher - Type 2", "Stained Glass Suncatcher - Type 2", 1],
            ["Stainless-20oz", "Stainless-20oz", 1],
            ["Sun Visor Clip Ken Nguyen", "Sun Visor Clip Ken Nguyen", 1],
            ["suncatcher", "suncatcher không file đen", 1],
            ["Suncatcher Acrylic Bookmark", "Suncatcher Acrylic Bookmark", 1],
            ["Suncatcher Art Piece", "Suncatcher Art Piece - có file đen", 1],
            ["Su Tron 1M GaXep", "Su Tron 1M GaXep", 1],
            ["Su Tron 1M nho", "Su Tron 1M nho", 1],
            ["Su Tron 2M nho", "Su Tron 2M nho", 1],
            ["tat", "tat", 1],
            ["tem normal", "in tem", 0],
            ["thot 5mm", "Thớt 5mm", 1],
            ["thot 5mm 2M", "Thớt 5mm 2 mặt", 2],
            ["thot amazone", "Thớt AMAZONE", 1],
            ["thot den", "Thớt Đen", 1],
            ["Tumble Name Tag", "Tumble Name Tag", 1],
            ["tranh trang guong", "tranh trang guong", 1],
            ["Wind Spinner", "Wind Spinner", 1],
            ["wine-12oz", "wine-12oz", 1],
            ["wood fix ornament 1M", "wood fix ornament 1M", 1],
            ["wood fix ornament 2M", "wood fix ornament 2M", 2],
            ["wood ornament dls", "wood ornament dls", 1],
            ["Wooden Block", "Wooden Block", 1],
            ["Wooden Parterre", "Wooden Parterre", 1],
            ["Wooden Picture Frame Magnet", "Wooden Picture Frame Magnet", 1],
            ["woodSignTwoSign", "Thớt 5mm 2 mặt", 2]
        ]
    ]
]